# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Golang learning
author: shipengqi
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-doc

theme_config:
  favicon: images/favicon.ico
url: http://www.shipengqi.top/golang-learn
root: /golang-learn/

deploy:
- type: git
  repo: git@github.com:shipengqi/golang-learn.git
  branch: gh-pages

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'